spring:
  data:
    mongodb:
      uri: mongodb://spring:etec123@ds131041.mlab.com:31041/etec

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200